name: Build Windows Version

on:
  workflow_dispatch: {}

jobs:
  linux-build:
    runs-on: windows-latest
    steps:
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: build
      run: |
          mkdir build
          go build -o ./build/phoenixbuilder.exe

    - name: upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: PhoenixBuilder
        path: ${{ GITHUB.WORKSPACE }}\build\
