name: Check

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  phoenixbuilder-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Install compilers
      run: |
        sudo apt update
        sudo apt install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc gcc-aarch64-linux-gnu libgl1-mesa-dev xorg-dev -y
    - name: Build PhoenixBuilder
      run: |
        make current
        make clean
        chmod 0777 ~/go/pkg/mod/github.com/sandertv/go-raknet@v1.12.0/
        sed -i "s/urrentProtocol byte = 11/urrentProtocol byte = 8/g" ~/go/pkg/mod/github.com/sandertv/go-raknet@v1.12.0/conn.go
        # make windows-executable-x86_64
        make current
    - name: upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: PhoenixBuilder
        path: ${{ GITHUB.WORKSPACE }}/build
