name: test

on:
  workflow_dispatch: {}

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    steps:
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      
    - name: list
      run: |
        cd ./omega_release/launcher
        make build
