name: test

on:
  workflow_dispatch: {}

jobs:
  linux-build:
    runs-on: windows-latest
    steps:
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: build
      run: |
        cd ./omega_release/launcher
        go build main.go
